# Homebrew formula for ninthwave.
#
# This is a reference formula kept in-repo. The canonical formula lives in
# the ninthwave-sh/homebrew-tap repository and is updated by the release
# workflow. Keep this file in sync with the tap formula.
#
# Install: brew install ninthwave-sh/tap/ninthwave
# Update:  brew upgrade ninthwave

class Ninthwave < Formula
  desc "Parallel AI coding orchestration — human-sized PRs"
  homepage "https://github.com/ninthwave-sh/ninthwave"
  url "https://github.com/ninthwave-sh/ninthwave/releases/download/v__VERSION__/ninthwave-__VERSION__-__OS__-__ARCH__.tar.gz"
  sha256 "__SHA256__"
  license "MIT"

  depends_on "nono"

  # Placeholder: on_macos / on_linux blocks with architecture-specific URLs
  # are generated by the release workflow (.github/workflows/release.yml).

  def install
    bin.install "ninthwave"
    # Short alias: `nw` is the daily-driver command (2 chars, no conflicts).
    # `ninthwave` remains the full name for docs and scripts.
    bin.install_symlink "ninthwave" => "nw"

    # Resource files (skills, agents, docs) used by `ninthwave setup`
    (share/"ninthwave").install Dir["*"] - ["ninthwave"]
  end

  test do
    assert_match "ninthwave", shell_output("#{bin}/ninthwave version")
    # Verify nw symlink works
    assert_match "ninthwave", shell_output("#{bin}/nw version")
  end
end
